spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: artifacts
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      database: ${SPRING_REDIS_DATABASE} # Which database to use? 0 - 15

server:
  port: ${SERVER_PORT}
